version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    groups:
      development-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: simplecov
        update-types:
          - version-update:semver-major
      - dependency-name: steep
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
