AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  UseCache: false
  Exclude:
    - "gemfiles/**/*"
    - "pkg/**/*"
    - "sig/generated/**/*"
    - "vendor/**/*"

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true
  AllowSteepAnnotation: true

Layout/LineLength:
  Max: 100
  AllowedPatterns:
    - "^\\s*#:"

Metrics/AbcSize:
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15
